--liquibase formatted sql

--changeset kmschoep:synonyms splitstatements:true
CREATE SYNONYM NEMI_DATA_APEX.METHOD_ONLINE_VW FOR NEMI_DATA.METHOD_ONLINE_VW;

CREATE SYNONYM NEMI_DATA_APEX.PROTOCOL_METHOD_ONLINE_REL FOR NEMI_DATA.PROTOCOL_METHOD_ONLINE_REL;

CREATE SYNONYM NEMI_DATA_APEX.PROTOCOL_METHOD_STG_REL FOR NEMI_DATA.PROTOCOL_METHOD_STG_REL;

CREATE SYNONYM NEMI_DATA_APEX.PROTOCOL_STG_VW FOR NEMI_DATA.PROTOCOL_STG_VW;

CREATE SYNONYM NEMI_DATA_APEX.SOURCE_CITATION_ONLINE_REF_SYN FOR NEMI_DATA.SOURCE_CITATION_ONLINE_REF;

--changeset kmschoep:ANALYTE_METHOD_JN_ONLINE splitstatements:false
CREATE OR REPLACE FORCE VIEW NEMI_DATA_APEX.ANALYTE_METHOD_JN_ONLINE
(ANALYTE_METHOD_ID, METHOD_ID, ANALYTE_ID, DL_VALUE, DL_UNITS,
ACCURACY, ACCURACY_UNITS, FALSE_POSITIVE_VALUE, FALSE_NEGATIVE_VALUE, PRECISION,
PRECISION_UNITS, PREC_ACC_CONC_USED, INSERT_DATE, INSERT_PERSON_NAME, LAST_UPDATE_DATE,
LAST_UPDATE_PERSON_NAME, GREEN_FLAG, YELLOW_FLAG, CONFIRMATORY, REVIEWER_NAME)
AS
SELECT "ANALYTE_METHOD_ID","METHOD_ID","ANALYTE_ID","DL_VALUE","DL_UNITS","ACCURACY","ACCURACY_UNITS","FALSE_POSITIVE_VALUE","FALSE_NEGATIVE_VALUE","PRECISION","PRECISION_UNITS","PREC_ACC_CONC_USED","INSERT_DATE","INSERT_PERSON_NAME","LAST_UPDATE_DATE","LAST_UPDATE_PERSON_NAME","GREEN_FLAG","YELLOW_FLAG","CONFIRMATORY","REVIEWER_NAME" 
FROM analyte_method_jn_online_syn

--changeset kmschoep:REVISION_JOIN_ONLINE splitstatements:false
CREATE OR REPLACE FORCE VIEW NEMI_DATA_APEX.REVISION_JOIN_ONLINE
(REVISION_ID, METHOD_ID, REVISION_INFORMATION, METHOD_PDF, INSERT_DATE,
INSERT_PERSON_NAME, LAST_UPDATE_DATE, LAST_UPDATE_PERSON_NAME, REVISION_FLAG, MIMETYPE,
PDF_INSERT_PERSON, PDF_INSERT_DATE, REVIEWER_NAME, SOURCE_CITATION_ID)
AS
SELECT "REVISION_ID","METHOD_ID","REVISION_INFORMATION","METHOD_PDF","INSERT_DATE","INSERT_PERSON_NAME","LAST_UPDATE_DATE","LAST_UPDATE_PERSON_NAME","REVISION_FLAG","MIMETYPE","PDF_INSERT_PERSON","PDF_INSERT_DATE","REVIEWER_NAME","SOURCE_CITATION_ID"
FROM revision_join_online_syn

--changeset kmschoep:REVISION_JOIN_STG splitstatements:false
CREATE OR REPLACE FORCE VIEW NEMI_DATA_APEX.REVISION_JOIN_STG
(REVISION_ID, METHOD_ID, REVISION_INFORMATION, METHOD_PDF, INSERT_DATE,
INSERT_PERSON_NAME, LAST_UPDATE_DATE, LAST_UPDATE_PERSON_NAME, MIMETYPE, PDF_INSERT_PERSON,
PDF_INSERT_DATE, REVISION_FLAG, DATE_LOADED, SOURCE_CITATION_ID)
AS
SELECT "REVISION_ID","METHOD_ID","REVISION_INFORMATION","METHOD_PDF","INSERT_DATE","INSERT_PERSON_NAME","LAST_UPDATE_DATE","LAST_UPDATE_PERSON_NAME","MIMETYPE","PDF_INSERT_PERSON","PDF_INSERT_DATE","REVISION_FLAG","DATE_LOADED","SOURCE_CITATION_ID"
FROM revision_join_stg_syn

--changeset kmschoep:SOURCE_CITATION_ONLINE_REF splitstatements:false
CREATE OR REPLACE FORCE VIEW NEMI_DATA_APEX.SOURCE_CITATION_ONLINE_REF
(SOURCE_CITATION_ID, SOURCE_CITATION, SOURCE_CITATION_NAME, SOURCE_CITATION_INFORMATION,INSERT_DATE,
TITLE, AUTHOR, ABSTRACT_SUMMARY, TABLE_OF_CONTENTS, LINK,
NOTES, ITEM_TYPE_ID, PUBLICATION_YEAR, COUNTRY, UPDATE_DATE,
ITEM_TYPE_NOTE, SPONSER_TYPE_NOTE, INSERT_PERSON_NAME, CITATION_TYPE, READY_FOR_REVIEW)
AS
SELECT "SOURCE_CITATION_ID","SOURCE_CITATION","SOURCE_CITATION_NAME","SOURCE_CITATION_INFORMATION","INSERT_DATE","TITLE","AUTHOR","ABSTRACT_SUMMARY","TABLE_OF_CONTENTS","LINK","NOTES","ITEM_TYPE_ID","PUBLICATION_YEAR","COUNTRY","UPDATE_DATE","ITEM_TYPE_NOTE","SPONSER_TYPE_NOTE","INSERT_PERSON_NAME","CITATION_TYPE","READY_FOR_REVIEW"
FROM source_citation_online_ref_syn

--changeset kmschoep:SOURCE_CITATION_REF splitstatements:false
CREATE OR REPLACE FORCE VIEW NEMI_DATA_APEX.SOURCE_CITATION_REF
(SOURCE_CITATION_ID, SOURCE_CITATION, SOURCE_CITATION_NAME, SOURCE_CITATION_INFORMATION,INSERT_PERSON_NAME,
INSERT_DATE, TITLE, AUTHOR, ABSTRACT_SUMMARY, TABLE_OF_CONTENTS,
LINK, NOTES, PUBLICATION_YEAR, COUNTRY, ITEM_TYPE_ID,
UPDATE_DATE, ITEM_TYPE_NOTE, SPONSER_TYPE_NOTE, CITATION_TYPE, APPROVED,
APPROVED_DATE)
AS
SELECT "SOURCE_CITATION_ID","SOURCE_CITATION","SOURCE_CITATION_NAME","SOURCE_CITATION_INFORMATION","INSERT_PERSON_NAME","INSERT_DATE","TITLE","AUTHOR","ABSTRACT_SUMMARY","TABLE_OF_CONTENTS","LINK","NOTES","PUBLICATION_YEAR","COUNTRY","ITEM_TYPE_ID","UPDATE_DATE","ITEM_TYPE_NOTE","SPONSER_TYPE_NOTE","CITATION_TYPE","APPROVED","APPROVED_DATE"
FROM source_citation_ref_syn

--changeset kmschoep:SOURCE_CITATION_STG_REF splitstatements:false
CREATE OR REPLACE FORCE VIEW NEMI_DATA_APEX.SOURCE_CITATION_STG_REF
(SOURCE_CITATION_ID, SOURCE_CITATION, SOURCE_CITATION_NAME, SOURCE_CITATION_INFORMATION,INSERT_DATE,
TITLE, AUTHOR, ABSTRACT_SUMMARY, TABLE_OF_CONTENTS, LINK,
NOTES, ITEM_TYPE_ID, PUBLICATION_YEAR, COUNTRY, UPDATE_DATE,
ITEM_TYPE_NOTE, SPONSER_TYPE_NOTE, INSERT_PERSON_NAME, CITATION_TYPE, READY_FOR_REVIEW,
OWNER_EDITABLE, APPROVED_DATE, APPROVED)
AS
SELECT "SOURCE_CITATION_ID","SOURCE_CITATION","SOURCE_CITATION_NAME","SOURCE_CITATION_INFORMATION","INSERT_DATE","TITLE","AUTHOR","ABSTRACT_SUMMARY","TABLE_OF_CONTENTS","LINK","NOTES","ITEM_TYPE_ID","PUBLICATION_YEAR","COUNTRY","UPDATE_DATE","ITEM_TYPE_NOTE","SPONSER_TYPE_NOTE","INSERT_PERSON_NAME","CITATION_TYPE","READY_FOR_REVIEW","OWNER_EDITABLE","APPROVED_DATE","APPROVED"
FROM source_citation_stg_ref_syn

