--liquibase formatted sql

--changeset kmschoep:production_mods


 ALTER TABLE NEMI_DATA.METHOD_SOURCE_REF
 ADD (DATA_ENTRY_NAME VARCHAR2(50 CHAR));

 ALTER TABLE NEMI_DATA.METHOD_SOURCE_REF
 ADD (DATA_ENTRY_DATE DATE);

 ALTER TABLE NEMI_DATA.METHOD_SOURCE_REF
 ADD (UPDATE_NAME VARCHAR2(50 CHAR));
 
 ALTER TABLE NEMI_DATA.METHOD_SOURCE_REF
 ADD (UPDATE_DATE DATE);


 ALTER TABLE NEMI_DATA.SOURCE_CITATION_REF
 ADD (UPDATE_NAME VARCHAR2(50 CHAR));

 ALTER TABLE NEMI_DATA.GREEN_METHOD_CHEMICALS
 ADD (METHOD_ID NUMBER(9));
 
 ALTER TABLE NEMI_DATA.METHOD_STG
 MODIFY(APPROVED DEFAULT 'N');

 ALTER TABLE NEMI_DATA.METHOD_STG
 ADD (NO_ANALYTE_FLAG VARCHAR2(1 CHAR) DEFAULT 'N');

 ALTER TABLE NEMI_DATA.METHOD_STG
 ADD (OWNER_EDITABLE VARCHAR2(1 CHAR) DEFAULT 'N');

 -- Missing Columns are added in separate ADD COLUMN statements

 ALTER TABLE NEMI_DATA.METHOD_STG_JN
 ADD (NO_ANALYTE_FLAG VARCHAR2(1 CHAR) DEFAULT 'N');

 ALTER TABLE NEMI_DATA.METHOD_STG_JN
 ADD (OWNER_EDITABLE VARCHAR2(1 CHAR) DEFAULT 'N');

--ALTER TABLE NEMI_DATA.ANALYTE_METHOD_JN_STG_JN DROP COLUMN ANALYTE_SPECIFICITY;

 -- Extra Columns are dropped in separate DROP COLUMN statements (Oracle 8i and newer)

 --ALTER TABLE NEMI_DATA.ANALYTE_METHOD_JN_ONLINE_JN DROP COLUMN ANALYTE_SPECIFICITY;
 
 
 ALTER TABLE NEMI_DATA.SOURCE_CITATION_ONLINE_REF
 ADD (UPDATE_NAME VARCHAR2(50 CHAR));

 -- Missing Columns are added in separate ADD COLUMN statements

 ALTER TABLE NEMI_DATA.SOURCE_CITATION_STG_REF_JN
 ADD (UPDATE_NAME VARCHAR2(50 CHAR));

 -- Missing Columns are added in separate ADD COLUMN statements

 ALTER TABLE NEMI_DATA.SOURCE_CITATION_ONLINE_REF_JN
 ADD (UPDATE_NAME VARCHAR2(50 CHAR));
 
 ALTER TABLE NEMI_DATA.SOURCE_CITATION_STG_REF
 ADD (UPDATE_NAME VARCHAR2(50 CHAR));

 ALTER TABLE NEMI_DATA.ACCURACY_UNITS_DOM
ADD (DATA_ENTRY_NAME VARCHAR2(50 CHAR));

 ALTER TABLE NEMI_DATA.ACCURACY_UNITS_DOM
 ADD (DATA_ENTRY_DATE DATE);

 ALTER TABLE NEMI_DATA.ACCURACY_UNITS_DOM
 ADD (UPDATE_NAME VARCHAR2(50 CHAR));

 ALTER TABLE NEMI_DATA.ACCURACY_UNITS_DOM
 ADD (UPDATE_DATE DATE);

 ALTER TABLE NEMI_DATA.ANALYTE_METHOD_JN DROP COLUMN ANALYTE_SPECIFICITY;

 ALTER TABLE NEMI_DATA.ANALYTE_METHOD_JN_ONLINE DROP COLUMN ANALYTE_SPECIFICITY;

 ALTER TABLE NEMI_DATA.DEFINITIONS_DOM
 ADD (COLUMN_HELP VARCHAR2(4000 CHAR));

 ALTER TABLE NEMI_DATA.DL_REF
 ADD (DATA_ENTRY_NAME VARCHAR2(50 CHAR));